version: "3.8"

services:
  keycloak:
    image: jboss/keycloak
    container_name: "keycloak"
    command: ["-Djboss.http.port=8081"]
    ports:
      - "8081:8081"
    volumes:
      - ./keycloak/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    networks:
      - project
  web:
    build: .
    container_name: "web"
    profiles:
      - web
    ports:
      - "8080:8080"
    links:
      - keycloak
    networks:
      - project
networks:
  project:
    driver: bridge