server:
  port: ${PORT:8080}

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    reactive:
      max-chunk-size: 8192
    cache: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        userInfoUri: ${KEY_CLOAK_URL:http://keycloak:8081}/auth/realms/hello-world-realm/protocol/openid-connect/userinfo
        jwt:
          issuer-uri: ${KEY_CLOAK_URL:http://keycloak:8081}/auth/realms/hello-world-realm
          jwk-set-uri: ${KEY_CLOAK_URL:http://keycloak:8081}/auth/realms/hello-world-realm/protocol/openid-connect/certs