spring:
  jpa:
    database: POSTGRESQL
  r2dbc:
    url: r2dbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      sslMode: REQUIRE
  flyway:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}?sslmode=require
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true