server:
  port: 9099

spring:
  thymeleaf:
    cache: false
  jpa:
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: h2
    url: jdbc:h2:file:./hello_world_db
    username: sa
    password:
    driverClassName: org.h2.Driver