server:
  port: ${PORT:8080}

spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true